# Generated by Django 2.2.6 on 2019-10-31 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundscapes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncircle',
            name='region_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='soundscapes.RegionMap'),
        ),
        migrations.AlterField(
            model_name='regioncircle',
            name='soundfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions_assigned_to', to='soundscapes.Soundfile'),
        ),
        migrations.AlterField(
            model_name='regionmap',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soundfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
