# Generated by Django 2.2.6 on 2019-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundscapes', '0003_auto_20191104_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncircle',
            name='soundfile',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
