# Generated by Django 2.2.6 on 2019-11-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundscapes', '0006_auto_20191105_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundfile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='soundfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='name',
            field=models.CharField(default='NO-NAME', max_length=100),
        ),
    ]
