# Generated by Django 2.2.6 on 2019-11-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundscapes', '0008_soundfile_analyzed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundfile',
            name='analyzed',
        ),
        migrations.AddField(
            model_name='soundfile',
            name='channels',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
