# Generated by Django 2.2.6 on 2019-11-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundscapes', '0009_auto_20191109_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfile',
            name='checksum',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='regioncircle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to=settings.AUTH_USER_MODEL),
        ),
    ]
